language: rust

rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy rustfmt

script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
